title: Sesha Sai Behara
url: "https://legolas96.github.io"
baseurl: "/index"

markdown: kramdown

tracking_id: #

footer: yes
footer_text: "Sesha's website"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/index"
 - name: "Resume"
   link: "/Curriculum_Vitae.pdf"
 - name: "Research"
   link: "/projects"
 - name: "Contact"
   link: "/contact"
